update guzzle lib to same version shopware uses
shopwareLabs/SwagMediaS3 pull request #11
Opened 2016-12-27 16:17 UTC by lhwparis

2016-12-28 07:41 UTC, mitelg requested changes

2016-12-28 07:41 UTC, mitelg commented on composer.json
> +        "guzzlehttp/guzzle": "~5.3"
please also update the composer.lock file

2016-12-28 07:42 UTC, mitelg commented
Hey @lhwparis, thanks for your PR :+1: 
please have a look at my comment :wink:

2016-12-28 07:50 UTC, lhwparis commented on composer.json
> +        "guzzlehttp/guzzle": "~5.3"
done :)

2016-12-28 09:23 UTC, mitelg approved these changes

2016-12-28 09:24 UTC, mitelg commented
looks good to me now, waiting for @janbuecker review

2016-12-28 09:25 UTC, lhwparis commented
thanks @mitelg :)

2017-01-26 11:18 UTC, lhwparis commented
@mitelg @janbuecker any news on merging that?

2017-02-01 07:48 UTC, janbuecker commented
Looks good to me. I'll import it and update guzzle to the current implemented Shopware version.

2017-02-01 08:08 UTC, closed without merging